
help:
	@echo "Usage:"
	@echo "- make doc : generate documentation"
	@echo "- make test : run unit tests"
#	@echo "- make rebind : rebind scripts to latest snippets"
#	@echo "  Sub options: make OPTS=flags rebind"
#	@echo "  - OPTS=-u : unbind files"
#	@echo "  - OPTS=--dry-run : do not modify files, just show what happens"
#	@echo "- make todo : check code completeness"

doc:
	make -C docs html


tests/Kyuafile: $(shell find tests -mindepth 1 -maxdepth 1 -name '*.sh' | xargs)
	(echo '-- Autogenerated file';echo 'syntax(2)';echo "test_suite('hoses')"; \
	x=;for s in $^ ; do x="$$(echo $$x $$(grep -q -e 'xatf_init' $$s && basename $$s))" ; done ; \
	for s in $$x ; do echo "atf_test_program{name='$$s'}" ; done ; \
	) > $@

test: tests/Kyuafile
	if type kyua ; then ( cd tests && kyua test ) ; fi

#~ rebind:
#~ 	$(BINDER) -R $(OPTS) scripts


#~ pkg/ashlib.sh: $(SNIPPETS) $(shell find pp -maxdepth 1 -type f '(' -name '*.sh' -o -name '*.bash' ')' | sed -e 's!^./!!')
#~ 	###$_begin-include: mk/upx.mk
#~ 	#
#~ 	# Compressed/executable
#~ 	#
#~ 		mkdir -p $$(dirname $@) ; \
#~ 		(echo '#!/bin/sh'; \
#~ 			[ -f VERSION ] && echo "# $$(basename "$@") $$(cat VERSION)" ; \
#~ 			[ -f ../VERSION ] && echo "# $$(basename "$@") $$(cat ../VERSION)" ; \
#~ 			echo '# src: ' ; \
#~ 			echo '$^' | fmt | sed -e 's/^/#      /' ; \
#~ 			echo '#' ; \
#~ 			echo 'eval "$$( (base64 -d | gzip -d) <<'\'_EOF_\' ; \
#~ 			(for x in $^; do \
#~ 				echo '###$$_include:' $$x ; done) \
#~ 				| $(BINDER) $(OPTS) \
#~ 				| gzip -9 | base64  ; \
#~ 			echo '_EOF_' ; echo ')"' ) > $@
#~ 	###$_end-include: mk/upx.mk

#~ pkg/pyus.py: $(shell find mypylib -maxdepth 1 -type f -name '*.py' | sed -e 's!^./!!')
#~ 	mkdir -p $$(dirname $@) ; \
#~ 	(echo '#!python3'; \
#~ 		echo '###$$_include: mypylib/pyus.in.py' ) | $(BINDER) > $@


#~ pkgs: pkg/ashlib.sh pkg/cgilib.sh pkg/pyus.py


